### ISSUE TITLE
Issue and PR template

### ISSUE THREAD

**Issue by Jothin-kumar** [sachinl0har/ALPHA-AI#2]
Please add an issue template and a PR template
Update: I have opened a PR #3. Merge it with the main branch, thank you!

**Comment by sachinl0har** [comment]
Added.. Nice Contribution 💯

**Comment by THe-CODIST-GAMER** [comment]
my error not opening any website on any command
[bug_report.md](https://github.com/sachinl0har/ALPHA-AI/files/13538545/bug_report.md)
